spring.application.name=email


server.port=8084

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yaravind817@gmail.com
spring.mail.password=xpfk nxvx ptfb ebva

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
