spring.application.name=BookingService


server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/bookingdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#jwt.secret=mysupersecretkeyforjwt123456


jwt.secret=replace_with_a_very_long_secret_at_least_32_chars!

debug = true

