spring.application.name=payment
server.port=8083


spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Must match the secret used by the other services
jwt.secret=replace_with_a_very_long_secret_at_least_32_chars!
